services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grpc-server
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - 
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17
    container_name: db_postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=image_storage
    # volumes:
    #   - ./pgData:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 10
