services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    environment:
      - DB_NAME=image_storage
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=pass
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=image_storage
#    volumes:
#      - /var/data:/var/lib/postgresql/data
    restart: always